name: CI setup for Go #Name the workflow
on: #on event
  push:
    branches: [main] #identifying branch
    
jobs: #jobs to execute on event
  my-ci-job-1:
    name: My CI Job
    runs-on: ubuntu-latest # OS in VM
    steps:
    - name: Print a greeting
      run: |
        echo Hello there! # run terminal command
