name: CI setup for Go #Name the workflow
on: #on event
  push:
    branches: [main] #identifying branch
    
jobs: #jobs to execute on event
  my-ci-job-1:
    name: My CI Job
    runs-on: ubuntu-18.04 # OS in VM
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! # run terminal command
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5
        
    - name: Show Go Version # verify that go is installed
      run: go version # show go version
      
    - name: My cURL Request 
      run: curl https://kwehbot.xyz/api/stats   
      
    - name: Checkout Code # bring repo code to vm
      uses: actions/checkout@v2     
      
    - name: Check File System # check vm has my files
      run: |
        ls
        cat calc.go # print the content of calc.go
